service: api-crud-test

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  environment:
    DYNAMO_TABLE_NAME: employees
    API_HEALTH: /health
    API_EMPLOYEE: /employee
    API_EMPLOYEES: /employees
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMO_TABLE_NAME}"

functions:
  apiCrudTest:
    handler: handler.apiCrudTest
    events:
      - http:
          path: health
          method: get
          cors: true
      - http:
          path: employees
          method: get
          cors: true
      - http:
          path: employee
          method: get
          cors: true
      - http:
          path: employee
          method: post
          cors: true
      - http:
          path: employee
          method: patch
          cors: true
      - http:
          path: employee
          method: delete
          cors: true

resources:
  Resources:
    EmployeesDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMO_TABLE_NAME}
